import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RootContainer from "@/components/shared/containers";

import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import languages from "@/constants/languages";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fa" }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  const lang = languages.find(({ symbol }) => symbol === locale);
  const dir: any = lang?.dir ?? "ltr";
  return (
    <html lang={locale} dir={dir}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <RootContainer locale={locale} dir={dir}>
            {children}
          </RootContainer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
